version: '3.9'
services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: coloringbook
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: coloringbook
      MYSQL_PASSWORD: colmybook
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-p${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10
    volumes:
      - sql-db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=coloringbook
      - MYSQL_PASSWORD=colmybook
      - MYSQL_DB=coloringbook
    volumes:
      - .:/coloringbook:rw

volumes:
  sql-db:

