version: '3.9'
services:
  db:
    image: mysql:5.7
    env_file: .env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-p${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10
    volumes:
      - sql-db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEVELOPMENT=${DEVELOPMENT}
        - CONFIG_FILE=${CONFIG_FILE}
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - .:/coloringbook:rw
  
  redis:
    image: redis:6.2
  
  worker:
    build: .
    command: celery -A make_celery worker --loglevel=info --uid=nobody --gid=nogroup
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CONFIG_FILE=${CONFIG_FILE}
    depends_on:
      - redis
      - db
    volumes:
      - .:/coloringbook:rw

volumes:
  sql-db:

