version: '3.9'
services:
  db:
    image: mysql:5.7
    env_file: .env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-p${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10
    volumes:
      - sql-db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEVELOPMENT=${DEVELOPMENT}
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - .:/coloringbook:rw

volumes:
  sql-db:

