version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: coloringbook
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: coloringbook
      MYSQL_PASSWORD: colmybook
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=coloringbook
      - MYSQL_PASSWORD=colmybook
      - MYSQL_DB=coloringbook
